#!/usr/bin/env python3
"""
Empire Silicium Matrix Analysis
===============================

Visualizes the correspondence matrix generated by the EmpireSiliciumMatrix model.
The heatmap shows the 'consonance' between ascending and descending structures
mapped across 96 points (12 notes * 8 octaves).
"""

import torch
import matplotlib.pyplot as plt
import seaborn as sns
from empire_silicium_matrix import EmpireSiliciumMatrix

def run_analysis():
    print("Generating Empire Silicium Matrix Analysis...")

    # Initialize model
    model = EmpireSiliciumMatrix()
    model.eval()

    # Inputs: All 96 tokens
    input_asc = torch.arange(96).unsqueeze(0)
    input_desc = torch.arange(96).unsqueeze(0)

    # Generate matrix
    with torch.no_grad():
        matrix = model(input_asc, input_desc).squeeze(0)

    # Plotting
    plt.figure(figsize=(12, 10))
    sns.heatmap(matrix.numpy(), cmap='magma', xticklabels=12, yticklabels=12)
    plt.title("Empire Silicium Correspondence Matrix (96x96)")
    plt.xlabel("Descending Structure (G)")
    plt.ylabel("Ascending Structure (F)")

    # Save the plot
    output_file = "matrix_analysis.png"
    plt.savefig(output_file)
    print(f"Analysis saved to {output_file}")

    # Optional: Display some statistics
    print(f"Matrix mean: {matrix.mean().item():.6f}")
    print(f"Matrix max: {matrix.max().item():.6f}")
    print(f"Matrix min: {matrix.min().item():.6f}")

if __name__ == "__main__":
    run_analysis()
