# ============================================================
# SYMBOLIC PRIME GEOMETRY — FIELD-LIKE EXTENSION
# ============================================================
#
#   V = S₁ ⊕ S_b
#
#   Analogous to:   C = R ⊕ iR
#
# ────────────────────────────────────────────────────────────
#
# SPACE DEFINITIONS:
#
#   S₁  — core nucleus space
#         Generated by nucleus traversals (abcg, and any word
#         that explicitly crosses through {a,b,c}).
#         Elements: primes ≤ c = 3  →  {a=1, b=2, c=3}
#         Role: real axis — stable, internally coherent.
#
#   S_b — break / transition operator space
#         Generated by def, efg, fgh and any transition
#         not contained within the nucleus.
#         Elements: primes > c = 3  →  {d,e,f,...,p}
#         Role: imaginary axis — structural deviation.
#         Not scalar-scalable: all S_b triplets have the
#         same action magnitude but reach different primes.
#
# ────────────────────────────────────────────────────────────
#
# WORD DECOMPOSITION:
#
#   For any partition ω, each transition (xᵢ → xᵢ₊₁) is
#   classified by where xᵢ and xᵢ₊₁ live:
#
#     Both ≤ 3          →  S₁ contribution  (α term)
#     At least one > 3  →  S_b contribution (β term)
#
#   The pair (α, β) are the coordinates of ω in V = S₁ ⊕ S_b.
#
#   Phase angle:   φ = arctan(β / α)    ∈ [0°, 90°]
#   Modulus:       |ω| = √(α² + β²)
#
# ────────────────────────────────────────────────────────────
#
# KEY RESULT:
#
#   The phase angle φ of a word ω and the binary availability
#   of its target prime are INDEPENDENT properties.
#
#   bh   → i=19  (binary ✓)   φ = 90°   pure S_b word
#   abcg → i=19  (binary ✓)   φ = 42°   S₁-dominant word
#
#   Two descriptions of the same prime sit at orthogonal
#   positions in V. The "binary" form is not in S₁ — it
#   lives in S_b. Only the nuclear form carries S₁ content.
#
#   abcdek → p=47 (binary ✗)  φ = 66°   combined regime
#
# ============================================================

import torch
import sys
import math
from itertools import combinations

# ────────────────────────────────────────────────────────────
# SYMBOL SPACE
# ────────────────────────────────────────────────────────────

SYMBOLS = {
    "a":  1, "b":  2, "c":  3, "d":  5, "e":  7,
    "f": 11, "g": 13, "h": 17, "i": 19, "j": 23,
    "k": 29, "l": 31, "m": 37, "n": 41, "o": 43, "p": 47,
}
REV        = {v: k for k, v in SYMBOLS.items()}
ALL_PRIMES = set(SYMBOLS.values())

# S₁ / S_b threshold: nucleus elements are those ≤ c = 3
S1_BOUND = SYMBOLS["c"]   # = 3


def encode(word: list[str]) -> torch.Tensor:
    return torch.tensor([SYMBOLS[s] for s in word], dtype=torch.float32)


def action_functional(x: torch.Tensor) -> dict:
    delta = x[1:] - x[:-1]
    abs_d = delta.abs()
    rho   = 1.0 / (abs_d + 1.0)
    terms = abs_d * rho
    return {"delta": delta, "abs_d": abs_d, "rho": rho,
            "terms": terms, "A": terms.sum()}


# ────────────────────────────────────────────────────────────
# CORE OPERATION: DECOMPOSE ω INTO (α, β) ∈ V = S₁ ⊕ S_b
# ────────────────────────────────────────────────────────────

def decompose(word: list[str]) -> dict:
    """
    Decomposes the action of ω into S₁ and S_b components.

    α = Σ terms where both endpoints ≤ S1_BOUND  (nucleus transitions)
    β = Σ terms where at least one endpoint > S1_BOUND  (break transitions)
    φ = arctan(β / α)   in degrees
    |ω| = sqrt(α² + β²)

    Returns coordinates (α, β, φ, |ω|) in V = S₁ ⊕ S_b.
    """
    x   = encode(word)
    r   = action_functional(x)
    alpha, beta = 0.0, 0.0
    crossings   = []

    for i, term in enumerate(r["terms"]):
        x_i = x[i].item()
        x_j = x[i + 1].item()
        t   = term.item()
        if x_i <= S1_BOUND and x_j <= S1_BOUND:
            alpha += t
        else:
            beta += t
            if x_i <= S1_BOUND < x_j:
                crossings.append(i)   # marks S₁ → S_b crossing

    phi    = math.degrees(math.atan2(beta, alpha)) if alpha > 0 else 90.0
    modulus = math.sqrt(alpha ** 2 + beta ** 2)
    target  = int(x.sum().item())
    binary  = (target - 2) in ALL_PRIMES

    return {
        "x":        x,
        "terms":    r["terms"],
        "alpha":    alpha,
        "beta":     beta,
        "A":        alpha + beta,
        "phi":      phi,
        "modulus":  modulus,
        "crossings": crossings,
        "target":   target,
        "binary":   binary,
    }


# ────────────────────────────────────────────────────────────
# I. SPACE PARTITION: which elements live in S₁ vs S_b?
# ────────────────────────────────────────────────────────────

def section_spaces():
    print("=" * 64)
    print("I.  SPACE PARTITION")
    print("    Elements ≤ 3 → S₁  |  Elements > 3 → S_b")
    print("=" * 64)

    s1_elements  = [(k, v) for k, v in sorted(SYMBOLS.items(), key=lambda x: x[1])
                    if v <= S1_BOUND]
    sb_elements  = [(k, v) for k, v in sorted(SYMBOLS.items(), key=lambda x: x[1])
                    if v > S1_BOUND]

    print(f"\n  S₁ elements (nucleus):  ", end="")
    print("  ".join(f"{k}={v}" for k, v in s1_elements))

    print(f"  S_b elements (breaks):  ", end="")
    print("  ".join(f"{k}={v}" for k, v in sb_elements))

    print(f"""
  Structural interpretation:
    S₁ = {{a,b,c}} = {{1,2,3}} — compact nucleus, unit steps
    S_b = all primes beyond c — break operators, complement jumps

  Key asymmetry:
    The sum a+b+c = 6 does not yield a prime.
    Every prime partition must exit S₁ — there are no
    prime-summing words contained entirely within S₁.
    S_b is not optional: it is structurally necessary.
""")


# ────────────────────────────────────────────────────────────
# II. WORD COORDINATES IN V = S₁ ⊕ S_b
# ────────────────────────────────────────────────────────────

def section_coordinates():
    print("=" * 64)
    print("II. WORD COORDINATES IN V = S₁ ⊕ S_b")
    print("=" * 64)

    words = {
        "bh":     (list("bh"),     "Level 1 — binary"),
        "abcg":   (list("abcg"),   "Level 1 — nuclear"),
        "def":    (list("def"),    "Break 1  — triplet"),
        "efg":    (list("efg"),    "Break 1b — triplet"),
        "fgh":    (list("fgh"),    "Break 2  — triplet"),
        "abcdek": (list("abcdek"), "Level 2 — nuclear"),
    }

    print(f"\n  {'WORD':<8} {'α (S₁)':>9} {'β (S_b)':>9} {'|ω|':>8} {'φ':>8}"
          f" {'TARGET':>8} {'BIN':>5}  ROLE")
    print(f"  {'-'*8} {'-'*9} {'-'*9} {'-'*8} {'-'*8}"
          f" {'-'*8} {'-'*5}  {'-'*22}")

    records = {}
    for name, (w, role) in words.items():
        r = decompose(w)
        records[name] = r
        target_str  = f"{REV[r['target']]}={r['target']}"
        bin_str     = "✓" if r["binary"] else "✗"
        print(f"  {name:<8} {r['alpha']:>9.4f} {r['beta']:>9.4f} "
              f"{r['modulus']:>8.4f} {r['phi']:>7.2f}°"
              f" {target_str:>8} {bin_str:>5}  {role}")

    print(f"""
  Two independent axes:
    φ  = phase angle of the WORD  (how it traverses V)
    binary = invertibility of the TARGET (admits p = b + q?)

  Critical observation:
    bh   → i=19 (binary ✓)   φ = 90°  pure S_b word
    abcg → i=19 (binary ✓)   φ = 42°  S₁-dominant word

  The binary form (bh) lives entirely in S_b.
  The nuclear form (abcg) carries genuine S₁ content.
  Two descriptions of the same prime — orthogonal positions in V.
""")

    return records


# ────────────────────────────────────────────────────────────
# III. NON-SCALABILITY OF S_b
# ────────────────────────────────────────────────────────────

def section_nonscalability():
    print("=" * 64)
    print("III. NON-SCALABILITY OF S_b")
    print("=" * 64)

    print(f"""
  In  iR:  i·r₁  and  i·r₂  differ by scalar ratio r₂/r₁.
  In  S_b: the break triplets def, efg, fgh are NOT scalar
           multiples of each other — they are structurally
           parallel, reaching different primes at equal action.
""")

    triplets = [
        ("def", list("def")),
        ("efg", list("efg")),
        ("fgh", list("fgh")),
    ]

    A_vals   = []
    phi_vals = []
    print(f"  {'WORD':<6} {'VALUES':<16} {'TARGET':>8} {'β=A':>9} {'φ':>8}  {'BINARY':>8}")
    print(f"  {'-'*6} {'-'*16} {'-'*8} {'-'*9} {'-'*8}  {'-'*8}")
    for name, w in triplets:
        r = decompose(w)
        A_vals.append(r["A"])
        phi_vals.append(r["phi"])
        vals    = [SYMBOLS[s] for s in w]
        target  = REV[r["target"]]
        bin_str = "✓" if r["binary"] else "✗"
        print(f"  {name:<6} {str(vals):<16} {target+'='+str(r['target']):>8} "
              f"{r['A']:>9.6f} {r['phi']:>7.1f}°  {bin_str:>8}")

    A_tensor = torch.tensor(A_vals)
    print(f"\n  Action range across triplets:  "
          f"[{A_tensor.min().item():.6f}, {A_tensor.max().item():.6f}]")
    print(f"  Variance: {A_tensor.var().item():.2e}  ← invariant under position shift")

    # Show ratio structure between triplets
    print(f"\n  Pairwise ratios (β_i / β_j):")
    for i, (n1, _) in enumerate(triplets):
        for j, (n2, _) in enumerate(triplets):
            if i < j:
                ratio = A_vals[i] / A_vals[j]
                print(f"    {n1} / {n2}  =  {ratio:.6f}  "
                      f"← {'scalar' if abs(ratio-1)<1e-5 else 'non-scalar'} "
                      f"relation, different targets")

    print(f"""
  Conclusion:
    The three S_b triplets are ISOMETRIC in action space
    (same β = 22/15 ≈ 1.467) but NOT scalar multiples:
    efg ≠ λ·def for any λ ∈ R\\ {{1}}.
    They form a discrete orbit in V — not a line.
""")


# ────────────────────────────────────────────────────────────
# IV. abcdek IN THE COMBINED REGIME
# ────────────────────────────────────────────────────────────

def section_combined_regime(records: dict):
    print("=" * 64)
    print("IV. abcdek IN THE COMBINED REGIME")
    print("=" * 64)

    r = records["abcdek"]
    x = r["x"]
    t = r["terms"]

    print(f"\n  abcdek = {x.tolist()}")
    print(f"\n  Transition-by-transition classification:\n")
    print(f"  {'i':>3}  {'(xᵢ → xᵢ₊₁)':>16}  {'region':>8}  {'term':>9}  {'→ space'}")
    print(f"  {'-'*3}  {'-'*16}  {'-'*8}  {'-'*9}  {'-'*8}")

    for i in range(len(x) - 1):
        xi   = int(x[i].item())
        xj   = int(x[i + 1].item())
        term = t[i].item()
        li, lj = REV[xi], REV[xj]
        in_s1_i = xi <= S1_BOUND
        in_s1_j = xj <= S1_BOUND
        if in_s1_i and in_s1_j:
            space = "S₁"
        elif in_s1_i:
            space = "CROSSING"
        else:
            space = "S_b"
        print(f"  {i:>3}  ({li}={xi} → {lj}={xj}){'':<3} "
              f"{space:>8}  {term:>9.4f}  → {'α' if space=='S₁' else 'β'}")

    print(f"\n  Coordinates in V:")
    print(f"    α (S₁ content)  =  {r['alpha']:.4f}")
    print(f"    β (S_b content) =  {r['beta']:.4f}")
    print(f"    |abcdek|        =  {r['modulus']:.4f}")
    print(f"    φ               =  {r['phi']:.2f}°")
    print(f"    binary(p=47)?   =  {'✓' if r['binary'] else '✗'}")

    print(f"\n  Compare with abcg:")
    r1 = records["abcg"]
    print(f"    α(abcg)   = {r1['alpha']:.4f}    (same S₁ nucleus content)")
    print(f"    β(abcg)   = {r1['beta']:.4f}    β(abcdek) = {r['beta']:.4f}")
    print(f"    φ(abcg)   = {r1['phi']:.2f}°     φ(abcdek) = {r['phi']:.2f}°")

    print(f"""
  Structural consequence:
    abcg and abcdek share the SAME S₁ nucleus content: α = 1.0
    But abcdek extends into S_b territory — absorbing {{d,e}}
    and reaching a target p=47 with no binary description.

  The S₁ component is preserved; the S_b component grows.
  The phase rotates from 42° toward 90° — not a new space,
  but a deeper penetration into the break regime.

  Unlike the complex plane (where iR is orthogonal to R),
  here S_b extends the same word structure — it is not
  orthogonal in syntax, only in action geometry.
""")


# ────────────────────────────────────────────────────────────
# V. BINARY AVAILABILITY AS INDEPENDENT AXIS
# ────────────────────────────────────────────────────────────

def section_binary_axis():
    print("=" * 64)
    print("V.  BINARY AVAILABILITY AS AN INDEPENDENT AXIS")
    print("=" * 64)

    print(f"""
  The full classification of a word ω requires TWO values:

    1. φ(ω)      — phase angle of the word in V = S₁ ⊕ S_b
    2. binary(p) — does the target prime admit p = b + q?

  These axes are INDEPENDENT. Example:

    Both bh and abcg reach i=19 (binary ✓)
    But bh has φ=90° and abcg has φ=42° — orthogonal positions.

  Full word map:
""")
    words = [
        ("bh",     list("bh")),
        ("abcg",   list("abcg")),
        ("def",    list("def")),
        ("efg",    list("efg")),
        ("fgh",    list("fgh")),
        ("abcdek", list("abcdek")),
    ]

    print(f"  {'WORD':<8} {'φ':>8}  {'binary':>8}  QUADRANT IN (φ, binary)")
    print(f"  {'-'*8} {'-'*8}  {'-'*8}  {'-'*30}")

    for name, w in words:
        r   = decompose(w)
        phi = r["phi"]
        b   = r["binary"]
        q   = ("S₁-like, invertible"     if phi < 45 and b     else
               "S₁-like, non-invertible" if phi < 45 and not b else
               "S_b-like, invertible"    if phi >= 45 and b    else
               "S_b-like, non-invertible")
        print(f"  {name:<8} {phi:>7.1f}°  {'✓' if b else '✗':>8}  {q}")

    print(f"""
  The quadrant "S₁-like, non-invertible" is currently empty —
  suggesting that low phase angle (strong S₁ nucleus content)
  correlates with binary-available targets in this range.

  This may be a structural constraint: words that stay close
  to the nucleus tend to reach primes with binary descriptions.
  Words that penetrate S_b deeply tend to reach primes without.
""")


# ────────────────────────────────────────────────────────────
# VI. V AS A PHASE-TRANSITION OPERATOR SPACE
# ────────────────────────────────────────────────────────────

def section_phase_transition():
    print("=" * 64)
    print("VI. S_b AS PHASE-TRANSITION OPERATOR SPACE")
    print("=" * 64)

    print(f"""
  In C = R ⊕ iR:
    Multiplication by i rotates by 90° — a SMOOTH operation.
    i² = -1: applying i twice inverts the real axis.

  In V = S₁ ⊕ S_b:
    S_b does not rotate — it TRANSFORMS the target structure.
    There is no "S_b²" that returns to S₁.
    S_b is a one-way operator: it generates primes that
    cannot be recovered via binary inversion.

  Evidence: applying the S_b triplet structure twice —
""")
    # What happens if we "compose" S_b triplets?
    # The target of def is j=23; what's the S_b word reaching j?
    # Is there a consecutive triplet summing to 47 (p)?
    vals = sorted(v for v in SYMBOLS.values() if v != 47)
    print(f"  Consecutive triplets reaching p=47:")
    found = False
    for i in range(len(vals)-2):
        a,b,c = vals[i], vals[i+1], vals[i+2]
        if a+b+c == 47:
            print(f"    {REV[a]+REV[b]+REV[c]} = [{a},{b},{c}] → 47")
            found = True
    if not found:
        print(f"    None — p=47 is not reachable by any consecutive triplet.")
        print(f"    S_b orbit (triplets) does not close on p=47.")

    print(f"""
  The S_b triplet orbit:  def→j  efg→l  fgh→n
  reaches j=23, l=31, n=41 — but not p=47.

  p=47 requires the COMBINED regime (abcdek):
    S₁ nucleus {'{a,b,c}'} + S_b extension {'{d,e}'} + complement k.

  This is the phase-transition:
    S₁ alone cannot reach p.
    S_b triplets cannot reach p.
    Only the combined structure V = S₁ ⊕ S_b reaches p.

  abcdek is not merely in both spaces —
  it is the structural witness that V is irreducible:
  neither S₁ nor S_b alone spans the full prime geometry.
""")


# ────────────────────────────────────────────────────────────
# VII. ACTION SPECTRUM AS MODULUS IN V
# ────────────────────────────────────────────────────────────

def section_modulus():
    print("=" * 64)
    print("VII. ACTION SPECTRUM — MODULUS DISTRIBUTION IN V")
    print("=" * 64)

    words = [
        ("bh",     list("bh")),
        ("abcg",   list("abcg")),
        ("def",    list("def")),
        ("efg",    list("efg")),
        ("fgh",    list("fgh")),
        ("abcdek", list("abcdek")),
    ]

    alphas  = []
    betas   = []
    moduli  = []
    names   = []

    print(f"\n  {'WORD':<8} {'α²':>9} {'β²':>9} {'|ω|²':>9} {'|ω|':>9}")
    print(f"  {'-'*8} {'-'*9} {'-'*9} {'-'*9} {'-'*9}")

    for name, w in words:
        r  = decompose(w)
        a2 = r["alpha"] ** 2
        b2 = r["beta"] ** 2
        m2 = a2 + b2
        m  = r["modulus"]
        alphas.append(r["alpha"])
        betas.append(r["beta"])
        moduli.append(m)
        names.append(name)
        print(f"  {name:<8} {a2:>9.4f} {b2:>9.4f} {m2:>9.4f} {m:>9.4f}")

    alpha_t = torch.tensor(alphas)
    beta_t  = torch.tensor(betas)
    mod_t   = torch.tensor(moduli)

    print(f"\n  S₁ component (α) statistics:")
    print(f"    unique values:  {sorted(set(round(a,4) for a in alphas))}")
    print(f"    α is binary: 0.0 or 1.0 — nucleus either absent or fully present")

    print(f"\n  S_b component (β) statistics:")
    print(f"    min β = {beta_t.min().item():.4f}  ({names[beta_t.argmin().item()]})")
    print(f"    max β = {beta_t.max().item():.4f}  ({names[beta_t.argmax().item()]})")
    print(f"    S_b triplet β = {betas[2]:.6f}  (invariant across def/efg/fgh)")

    print(f"\n  Modulus spectrum:")
    for i, name in enumerate(names):
        bar_len = int(moduli[i] * 10)
        bar = "█" * bar_len
        print(f"    {name:<8}  |ω| = {moduli[i]:.4f}  {bar}")


def run_all():
    print()
    print("=" * 64)
    print("  SYMBOLIC PRIME GEOMETRY — FIELD-LIKE EXTENSION")
    print("  V = S₁ ⊕ S_b")
    print()
    print("  a=1  b=2  c=3  d=5  e=7  f=11  g=13  h=17  i=19")
    print("  j=23 k=29 l=31 m=37 n=41 o=43  p=47")
    print("=" * 64)

    section_spaces()
    records = section_coordinates()
    section_nonscalability()
    section_combined_regime(records)
    section_binary_axis()
    section_phase_transition()
    section_modulus()

    print()
    print("=" * 64)
    print("  STRUCTURAL SUMMARY")
    print("=" * 64)
    print("""
  V = S₁ ⊕ S_b  encodes two independent geometric properties:

  1. PHASE ANGLE φ  (property of the word)
     φ = 0°   → pure nucleus traversal (unreachable: no prime
                  sums within {a,b,c})
     φ = 42°  → abcg — maximal S₁ content among prime words
     φ = 66°  → abcdek — combined regime
     φ = 90°  → bh, def, efg, fgh — pure S_b trajectories

  2. BINARY AVAILABILITY  (property of the target prime)
     ✓ → target p admits p = b + q  (S₁ invertible target)
     ✗ → no such q exists           (S_b terminal)

  3. NON-SCALABILITY OF S_b
     def, efg, fgh: same β = 22/15, different primes.
     S_b acts as a discrete orbit, not a continuous line.

  4. IRREDUCIBILITY OF V
     p=47 requires both S₁ (nucleus) and S_b (extension).
     Neither space alone generates abcdek's target.
     V = S₁ ⊕ S_b is the minimal structure for Level 2.

  5. UNEXPECTED RESULT
     The binary form (bh) has φ = 90°: it lives in S_b.
     The nuclear form (abcg) has φ = 42°: it lives in S₁.
     Simplicity of description ≠ structural simplicity.
     The "longer" word is the more symmetric one.
""")

# ------------------------------------------------------------
# MAIN
# ------------------------------------------------------------

if __name__ == "__main__":
    if "--simulate" in sys.argv or len(sys.argv) == 1:
        run_all()
